name: build-and-test

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: RelWithDebInfo
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
        cxx: [g++-11]
        cc: [gcc-11]

    steps:
      - uses: actions/checkout@v2
      - name: Dependency setup
        run: |
            sudo apt update
            sudo apt install gcc-11 g++-11 ninja-build
      - name: Build
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
            ./build/abc.sh clean build
      - name: Test
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
            ./build/abc.sh test
